### PR TITLE
Fix for usage in Engines and nested addons, remove the need for htmlb…

### PR DESCRIPTION
**Pull request by vlascik**
…ars plugin

### CODE REVIEW

**Comment by tim-evans** [comment]
Hmm. This will collide with any variable named `title`. Is there any way to allow the AST transforms work with this?

**Comment by vlascik** [comment]
Well, I'd say that's kind of expected when you use a helper named `title`, but I can see the problem. It doesn't work if you include htmlbars into the nested addon's `dependencies` instead of `devDependencies`, but I'm afraid I don't know enough about Ember internals to fix it. Maybe you could try it with Engines demo apps? https://github.com/dgeb/ember-engines-demo and https://github.com/dgeb/ember-blog-engine

**Comment by tim-evans** [comment]
I added `ember-cli-htmlbars` as a direct dependency of `ember-page-title`: https://github.com/tim-evans/ember-page-title/commit/da9af61447aa152415268bdc3b22b78422dcc3ba

**Comment by tim-evans** [comment]
If this doesn't resolve the issue, please open a new issue :)

**Pull request closed without merging**
