### PR TITLE
Handle copy deprecation

### LINKED ISSUE #129: Copy Deprecation - Ember 3.3
copy() has been deprecated in favor of the ember-copy

```
DEPRECATION: Use ember-copy addon instead of copy method and Copyable mixin. [deprecation id: ember-runtime.deprecate-copy-copyable] See ht
tps://emberjs.com/deprecations/v3.x/#toc_ember-runtime-deprecate-copy-copyable for more details.\n        at logDeprecationStackTrace (http:
//localhost:7357/assets/vendor.js:25079:29)\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:25181:17)\n   
     at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:25103:17)\n        at HANDLERS.(anonymous function) (http://localhost:735
7/assets/vendor.js:25181:17)\n        at invoke (http://localhost:7357/assets/vendor.js:25190:17)\n        at deprecate (http://localhost:73
57/assets/vendor.js:25162:34)\n        at copy (http://localhost:7357/assets/vendor.js:60519:47)\n        at Class.remove (http://localhost:
7357/assets/vendor.js:218704:28)\n        at Class.destroy (http://localhost:7357/assets/vendor.js:218565:14)'
```

### PR DESCRIPTION
**Pull request by scottkidder**
Fixes #129

### CODE REVIEW

**Comment by bgentry** [comment]
The test failure here looks like a network flake. Are you able to re-trigger it @scottkidder?  Thanks for fixing this :pray:

**Comment by tim-evans** [comment]
Nice! I’d prefer to write a tiny structured clone here. Also valid, (if overly clever) is:

```js
JSON.parse(JSON.stringify(tokens))
```

Less dependencies is 🌈 for me

**Comment by scottkidder** [comment]
`JSON.parse(JSON.stringify(tokens))` was a no go due to circular structure. One test related to prepend is still failing.

**Comment by scottkidder** [comment]
Still have the prepend test failing. I'm not sure what could be causing this.

**Pull request merged**
