### PR TITLE
Prevent embedding '<!-- -->' If separator is not used

### PR DESCRIPTION
**Pull request by timur-sh**

### CODE REVIEW

**Comment by tim-evans** [comment]
Which version are you running on?

**Comment by timur-sh** [comment]
I'm running 1.1.11 version

**Comment by tim-evans** [comment]
Thanks! As a follow up, what version of Ember are you on?

**Comment by timur-sh** [comment]
My version Ember is 1.12.0

**Comment by tim-evans** [comment]
Oh man. I'm not sure if I want to support this version.

**Comment by timur-sh** [comment]
No problem. Thank you for your work!

**Pull request closed without merging**
