### PR TITLE
Prevent TypeError: Cannot read property 'length' of undefined in visibleTokens()

### PR DESCRIPTION
**Pull request by vlascik**

### CODE REVIEW

**Comment by thijsvdanker** [comment]
I ran into the same issue this morning, and the PR looks clean to me.
Could this be merged in?

**Comment by bladnman** [comment]
Oh great catch. *bump*

**Comment by tim-evans** [comment]
I'm not sure how to get into this state. Could someone provide a test case for this, just so I can understand what's going wrong here?

😅

**Comment by vlascik** [comment]
I think it was too random, I wasn't able to replicate it reliably, I was using this from ember engines back then, might have something to do with it, but I'm not sure. In the end I just added this check, which fixed it. I can let you know if it reappears.

**Comment by mazondo** [comment]
I'm currently in this state on version 2.0.7, also can't upgrade to newest due to https://github.com/tim-evans/ember-page-title/issues/36

Happy to help debug and find the cause

**Comment by mazondo** [comment]
Can confirm this fix resolved the issue for me, page titles all working as well.

**Comment by tim-evans** [comment]
Thanks for the reports, all!
Released in 3.0.3.

**Pull request merged**
