### PR TITLE
Don’t set document.title when running in FastBoot

### PR DESCRIPTION
**Pull request by rlivsey**

### CODE REVIEW

**Comment by tim-evans** [comment]
I would actually like this to work with fastboot properly, so apps running fastboot work with this addon out of the box.

@tomdale, could you suggest any approaches here? I'm not too familiar with fastboot, and don't know what the best approach for this would be.

**Comment by buschtoens** [comment]
Relevant code from [`ember-fastboot-server`](https://github.com/ember-fastboot/ember-fastboot-server/blob/a47e8d22f587ebe7281d989d0dcd92e12ff82b96/lib/server.js#L58-L69):

```js
FastBootServer.prototype.insertIntoIndexHTML = function(title, body, head) {
  var html = this.html.replace("<!-- EMBER_CLI_FASTBOOT_BODY -->", body);

  if (title) {
    html = html.replace("<!-- EMBER_CLI_FASTBOOT_TITLE -->", "<title>" + title + "</title>");
  }
  if (head) {
    html = html.replace("<!-- EMBER_CLI_FASTBOOT_HEAD -->", head);
  }

  return html;
};
```

**Comment by buschtoens** [comment]
The `title`, `body` and `head` arguments can be traced back to [`ember-app.js#L113-L136`](https://github.com/ember-fastboot/ember-fastboot-server/blob/a47e8d22f587ebe7281d989d0dcd92e12ff82b96/lib/ember-app.js#L113-L136):

```js
/*
 * After the ApplicationInstance has finished rendering, serializes the
 * resulting DOM element into HTML to be transmitted back to the user agent.
 */
function serializeHTML(doc, rootElement) {
  return function(instance) {
    var head;

    if (doc.head) {
      head = HTMLSerializer.serialize(doc.head);
    }

    try {
      return {
        url: instance.getURL(), // TODO: use this to determine whether to 200 or redirect
        title: doc.title,
        head: head,
        body: HTMLSerializer.serialize(rootElement) // This matches the current code; but we probably want `serializeChildren` here
      };
    } finally {
      instance.destroy();
    }
  };
}
```

`doc`, in this case, is a [`simple-dom.Document`](https://github.com/krisselden/simple-dom/blob/master/lib/simple-dom/document.js).

In theory, `ember-page-title` should be compatible out of the box - at least it shouldn't throw. However, the order of

```js
  if (title) {
    html = html.replace("<!-- EMBER_CLI_FASTBOOT_TITLE -->", "<title>" + title + "</title>");
  }
  if (head) {
    html = html.replace("<!-- EMBER_CLI_FASTBOOT_HEAD -->", head);
  }
```

should probably be reversed, so `document.title` takes precedence over the `<head>` inner HTML. Or am I missing something?

**Comment by buschtoens** [comment]
https://github.com/ember-fastboot/ember-fastboot-server/issues/32

**Comment by tomdale** [comment]
@buschtoens The current order makes sense to me, but maybe we're thinking about it differently.

`<title>` is, by definition, subordinate to `<head>`. That is a `<title>` will always live inside a `<head>`, but a `<head>` may not necessarily have a `<title>`.

We added a convenience for `<title>`, since it's so common, but my feeling is that if you're specifying a `<head>` you can also specify a `<title>`. In any case, I think the presence of `<title>` clobbering `<head>` (as I think happens in the PR submitted) seems like it would surprise the end developer.

One thing that might be nice would be to have `ember-page-title` work in conjunction with https://github.com/ronco/ember-cli-head. But there's a general composability problem here and I would love some help thinking through it.

**Comment by tim-evans** [comment]
Sounds great! I'd be happy to help with this process to get ember-page-title and ember-cli-head working together

**Comment by tomdale** [comment]
Paging @ronco

**Comment by ronco** [comment]
@tim-evans Can you hit me up on the ember community slack.  I'd love to talk through this with you, I need to tackle it myself for a couple other addons.

**Comment by ronco** [comment]
@tomdale,
@tim-evans just had a chat and here's the plan we're thinking of executing.  Please let us know what you think.

Update ember-cli-head to have basic title support.  This would be analogous to the simple title that was originally included in the ember-cli default index.html.  We would update the default `head.hbs` to:
```
<!-- `app/templates/head.hbs` -->
<!-- Add content you wish automatically added to the documents head -->
<!-- here. The 'model' available in this template can be populated by -->
<!-- setting values on the 'head-data' service. -->
<title>{{model.title}}</title>
```

Then ember-page-title can depend upon ember-cli-head, and update it's internal logic to set `title` on the `head-data` service.

**Comment by ronco** [comment]
@tim-evans I started looking into the updates to `ember-cli-head` as we discussed, and it became evident that won't be necessary.  We should be able to achieve FastBoot compatibility completely within this addon by using `ember-cli-head`.  I'll have a PR ready shortly, just ironing out the kinks.

**Comment by tim-evans** [comment]
Awesome. I looked through some of the code today, and saw that it was going to be super easy (just changing the `page-title` helper)

**Comment by tim-evans** [comment]
Closed by https://github.com/tim-evans/ember-page-title/pull/27.

This may require a minor change to your existing app. See https://github.com/tim-evans/ember-page-title#post-install-cleanup for more details :tada:

**Pull request closed without merging**
